### ISSUE TITLE
Instamojo : Not working in sandbox mode

### ISSUE THREAD

**Issue by vachan** [wpindiaorg/camptix-indian-payments#1]
When the **Instamojo** class is set in the **_Sandbox Mode_** it does not do any activity after _CampTix checkout_.

**Comment by sanyogs** [comment]
Hello Vachan

please describe more about step by step about this issue which you raised. So i can troubllshoot and fixed the issue.

**Comment by sanyogs** [comment]
Hello Vachan

this issue is fixed with following commit 
https://github.com/wpindiaorg/camptix-indian-payments/commit/79f8b9333a585bb33b6860b48fdb3591b1e3dc49

**Comment by vachan** [comment]
I am Still getting **_Invalid Insatmojo Access Key & Token_** in the **sandbox mode**
